### ISSUE TITLE
no basestring in Python 3 (and, Travis lies)

### ISSUE THREAD

**Issue by zackmdavis** [kirbyfan64/hytest#8]
(I'm not using hytest for a project or anything, but noticed this while hoping to understand more about the mysterious matter of the 256 phantom lines discussed in hylang/hy issue no. 742.) Python 3 doesn't have the `basestring` type referenced in `cmp-base`, causing a number of the self-tests to fail, but the project's CI still [reports success](https://travis-ci.org/kirbyfan64/hytest/jobs/59807130). (Looks like hytest.hy's `main` is returning `None`, which isn't an integer, so that the `hytest` wrapper doesn't notice anything is wrong?)

```
zmd@ExpectedReturn:~/Code/Examination/hytest$ python3 -c "import sys; print(sys.version_info)"
sys.version_info(major=3, minor=4, micro=0, releaselevel='final', serial=0)
zmd@ExpectedReturn:~/Code/Examination/hytest$ python3 hytest
test_hytest.hy ....FFFFFFF.F.

*******************************
ERROR: test_hytest.hy:test_cmp:
*******************************
Traceback (most recent call last):
  File "/home/zmd/Code/Examination/hytest/hytest.hy", line 2323, in main
  File "test_hytest.hy", line 23, in test_cmp
    (test-set test-cmp
  File "test_hytest.hy", line 279, in _hy_anon_fn_8
NameError: name 'basestring' is not defined

[more, similar errors redacted]

Tests run: 14
Tests succeeded: 6
Tests failed: 8
Tests skipped: 0
zmd@ExpectedReturn:~/Code/Examination/hytest$ echo $?
0
```

**Comment by kirbyfan64** [comment]
ARGH! I'll fix this when I get access to a computer in a few

**Comment by kirbyfan64** [comment]
Should be fixed now!

**Comment by kirbyfan64** [comment]
@zackmdavis Also a tip: the line numbers that Hy gives that are invalid are always the real line number added to some multiple of 256. Unfortunatel,  that's the furthest I was able to look into. It can seem like the factor 256 is multiplied by is somehow proportional to some of the Hy models. See my latest commit to Hyskell for an example. Adding an explicit replace removed 256 from the line number in the tests and corrected it.

Hope that helps a bit! Good luck!
